name: Build and Deploy to AWS ECR

on:
  push:
    branches:
      - main  # or your desired branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # You can remove this line if you don't want to use a specific runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change this to your desired AWS region

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-1  # Add the region here, replace with your region

      - name: Build and tag Docker image
        run: |
          docker build -t devops-proj .
          docker tag devops-proj:latest public.ecr.aws/h2i8y0n3/devops-proj:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push public.ecr.aws/h2i8y0n3/devops-proj:latest
