name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow from

jobs:
  docker-build-push:
    runs-on: ubuntu-latest  # You can change this if you don't need Ubuntu, but it's usually safe to leave it as is.

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up AWS CLI and authenticate
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1  # Change this to the region of your ECR repository

      # Step 3: Log in to AWS ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t public.ecr.aws/h2i8y0n3/devops-proj:latest .

      # Step 5: Push the Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          docker push public.ecr.aws/h2i8y0n3/devops-proj:latest
